language: java
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token
services:
  - postgresql
before_install:
  - chmod +x mvnw
before_script:
  - psql -c 'create database lingo;' -U postgres
after_success:
  - bash <(curl -s https://codecov.io/bash)